[package]
name = "cch23-cjharries25519"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.6.20"
axum-test = "13.4.1"
serde = "1.0.193"
shuttle-axum = "0.34.0"
shuttle-runtime = "0.34.0"
tokio = "1.28.2"
tracing = "0.1.40"

[dev-dependencies]
serde_json = "1.0.108"
